steps:
  - label: ":bazel: Build"
    commands:
      - echo "Building..."
  - label: ":bazel: Test 1"
    commands:
      - buildkite-agent meta-data set 'channel_for_help' '<https://pinterest.slack.com/test1|#test2>'
      - echo "Testing..."
  - label: ":bazel: Test 2"
    commands:
      - buildkite-agent meta-data set 'channel_for_help' '<https://pinterest.slack.com/test2|#test2>'
      - bazel test //main:hello-world-test
